version: "3.9"

services:
    db:
        container_name: mariadb
        build: ./mariadb
        ports:
            - 3306:3306
        env_file:
            - .env
        volumes:
            - mariadb_volume:/var/lib/mysql/
        restart: always

    wordpress:
        container_name: wordpress
        depends_on:
            - db
        build: ./wordpress
        env_file:
            - .env
        volumes:
            - wordpress_volume:/var/www/html
        restart: always

    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - 443:443
        volumes:
            - wordpress_volume:/var/www/html
        depends_on:
            - wordpress
        restart: always

volumes:
    wordpress_volume:
        driver: local
        driver_opts:
            type: none
            device: /home/jumaison/data/wordpress
            o: bind

    mariadb_volume:
        driver: local
        driver_opts:
            type: none
            device: /home/jumaison/data/mariadb
            o: bind
